export const DUAL_DEPOSIT_ESCROW_ABI = [
  {
    type: 'function',
    name: 'createEscrow',
    inputs: [
      { name: '_seller', type: 'address' },
      { name: '_arbiter', type: 'address' },
      { name: '_durationSeconds', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'acceptEscrow',
    inputs: [{ name: '_escrowId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'deliverWork',
    inputs: [
      { name: '_escrowId', type: 'uint256' },
      { name: '_deliveryHash', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'completeEscrow',
    inputs: [{ name: '_escrowId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimAfterDelivery',
    inputs: [{ name: '_escrowId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'disputeEscrow',
    inputs: [{ name: '_escrowId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'refundEscrow',
    inputs: [{ name: '_escrowId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveDispute',
    inputs: [
      { name: '_escrowId', type: 'uint256' },
      { name: '_buyerWins', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'escrows',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'buyer', type: 'address' },
      { name: 'seller', type: 'address' },
      { name: 'arbiter', type: 'address' },
      { name: 'paymentAmount', type: 'uint256' },
      { name: 'sellerStake', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
      { name: 'deliveryTime', type: 'uint256' },
      { name: 'deliveryHash', type: 'bytes32' },
      { name: 'state', type: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextEscrowId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalBurned',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'GRACE_PERIOD',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
